# Generated by Django 4.2 on 2023-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Billing',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('products', models.CharField(max_length=200)),
        #         ('quantity', models.IntegerField()),
        #         ('price', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Customer',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('total_bill', models.IntegerField()),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        # ),
        # migrations.RenameField(
        #     model_name='product',
        #     old_name='productname',
        #     new_name='name',
        # ),
    ]
