# Generated by Django 4.2 on 2023-04-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_orderline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
